name: pr1-node-backend
on: workflow_dispatch
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Print Success
        run: echo 'Success'
      - name: Print Goodbye
        run: echo 'Goodbye'
